### ISSUE TITLE
[Lint] Use always_specify_types instead.

### ISSUE THREAD

**Issue by MahanRahmati** [ubuntu-flutter-community/safe_change_notifier#3]
Using [always_specify_types](https://dart-lang.github.io/linter/lints/always_specify_types.html) makes reading code on the web easier.

**Comment by jpnurmi** [comment]
Hi, thanks for the proposal. Sorry for silently ignoring this for a week, I just wasn't sure how to respond to this.

Personally, I'm not strongly against using explicit types, and actually, that would've been my preference a few years ago, too. However, based on my experience, it's more common for Flutter projects to not use them mainly due to dartfmt's 80-character line wrap limit. I've learned to live with less verbose typing and kind of started appreciating that it results in less line-wrapping and comma-madness. :)

While this change doesn't make a difference in terms of wrapping in the code base of this specific project, I don't see a compelling reason to stylistically deviate from other Flutter and Dart projects in ubuntu/\*, ubuntu-flutter-community/\* and canonical/*. Once we start adding explicit types to all those apps where we are looking up view model providers etc. all over the place, we'll end up with lots of lines that wrap only and only because they mention the same view model type twice on the same line... Therefore, I'm leaning towards leaving it as is, for the sake of consistency.
